name: Failpoint test
on: [push, pull_request]
permissions: read-all
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17.13"
      - run: |
          make gofail-enable
          make test-failpoint

