#
# Automatically tag a merge with master, or build a new image from the tag.
#

name: Release

on:
  push:
    branches:
      - release
    #paths-ignore:
    #  - "docs/**"

jobs:
  tag-build-publish:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0" # make sure we get all commits!

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: release
          WITH_V: true
