blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using rawhttp
    url: https://github.com/projectdiscovery/rawhttp/discussions/categories/q-a
    about: Ask a question or request support for using rawhttp

  - name: Share idea / feature to discuss for rawhttp
    url: https://github.com/projectdiscovery/rawhttp/discussions/categories/ideas
    about: Share idea / feature to discuss for rawhttp

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication