blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using retryabledns
    url: https://github.com/projectdiscovery/retryabledns/discussions/categories/q-a
    about: Ask a question or request support for using retryabledns

  - name: Share idea / feature to discuss for retryabledns
    url: https://github.com/projectdiscovery/retryabledns/discussions/categories/ideas
    about: Share idea / feature to discuss for retryabledns

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication