name: Check Revision

on:
  schedule:
    - cron: '0 0 1 * *' # monthly

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - uses: actions/checkout@v3

      - run: |
          go run ./lib/launcher/revision
          go generate
