name: Check Issues

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - uses: actions/checkout@v3

      - name: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd lib/utils/check-issue && go run .
