blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using dnsx
    url: https://github.com/projectdiscovery/dnsx/discussions/categories/q-a
    about: Ask a question or request support for using dnsx

  - name: Share idea / feature to discuss for dnsx
    url: https://github.com/projectdiscovery/dnsx/discussions/categories/ideas
    about: Share idea / feature to discuss for dnsx

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication