sudo: false

language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

matrix:
  allow_failures:
    - go: tip

arch:
  - amd64
  - ppc64le

env: GO111MODULE=on

before_install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest

script:
  - make
