blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using chaos-client
    url: https://github.com/projectdiscovery/chaos-client/discussions/categories/q-a
    about: Ask a question or request support for using chaos-client

  - name: Share idea / feature to discuss for chaos-client
    url: https://github.com/projectdiscovery/chaos-client/discussions/categories/ideas
    about: Share idea / feature to discuss for chaos-client

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication