blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using useragent
    url: https://github.com/projectdiscovery/useragent/discussions/categories/q-a
    about: Ask a question or request support for using useragent

  - name: Share idea / feature to discuss for useragent
    url: https://github.com/projectdiscovery/useragent/discussions/categories/ideas
    about: Share idea / feature to discuss for useragent

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication