name: Check Examples

on:
  schedule:
    - cron: '23 3 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - uses: actions/checkout@v3

      - run: |
          go test -run Example ./...
          go test ./lib/examples/e2e-testing
