on:
  schedule:
    - cron:  '0 1 1 * *'  # UTC 01:00 on the first day of the Month

name: Release
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Release
        run: make release
